require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Ana. As you add validations to Ana, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all anas as @anas" do
      ana = Ana.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:anas)).to eq([ana])
    end
  end

  describe "GET #show" do
    it "assigns the requested ana as @ana" do
      ana = Ana.create! valid_attributes
      get :show, {:id => ana.to_param}, valid_session
      expect(assigns(:ana)).to eq(ana)
    end
  end

  describe "GET #new" do
    it "assigns a new ana as @ana" do
      get :new, {}, valid_session
      expect(assigns(:ana)).to be_a_new(Ana)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ana as @ana" do
      ana = Ana.create! valid_attributes
      get :edit, {:id => ana.to_param}, valid_session
      expect(assigns(:ana)).to eq(ana)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Ana" do
        expect {
          post :create, {:ana => valid_attributes}, valid_session
        }.to change(Ana, :count).by(1)
      end

      it "assigns a newly created ana as @ana" do
        post :create, {:ana => valid_attributes}, valid_session
        expect(assigns(:ana)).to be_a(Ana)
        expect(assigns(:ana)).to be_persisted
      end

      it "redirects to the created ana" do
        post :create, {:ana => valid_attributes}, valid_session
        expect(response).to redirect_to(Ana.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ana as @ana" do
        post :create, {:ana => invalid_attributes}, valid_session
        expect(assigns(:ana)).to be_a_new(Ana)
      end

      it "re-renders the 'new' template" do
        post :create, {:ana => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ana" do
        ana = Ana.create! valid_attributes
        put :update, {:id => ana.to_param, :ana => new_attributes}, valid_session
        ana.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ana as @ana" do
        ana = Ana.create! valid_attributes
        put :update, {:id => ana.to_param, :ana => valid_attributes}, valid_session
        expect(assigns(:ana)).to eq(ana)
      end

      it "redirects to the ana" do
        ana = Ana.create! valid_attributes
        put :update, {:id => ana.to_param, :ana => valid_attributes}, valid_session
        expect(response).to redirect_to(ana)
      end
    end

    context "with invalid params" do
      it "assigns the ana as @ana" do
        ana = Ana.create! valid_attributes
        put :update, {:id => ana.to_param, :ana => invalid_attributes}, valid_session
        expect(assigns(:ana)).to eq(ana)
      end

      it "re-renders the 'edit' template" do
        ana = Ana.create! valid_attributes
        put :update, {:id => ana.to_param, :ana => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ana" do
      ana = Ana.create! valid_attributes
      expect {
        delete :destroy, {:id => ana.to_param}, valid_session
      }.to change(Ana, :count).by(-1)
    end

    it "redirects to the anas list" do
      ana = Ana.create! valid_attributes
      delete :destroy, {:id => ana.to_param}, valid_session
      expect(response).to redirect_to(anas_url)
    end
  end

end
